"""Write docs/build-kit/reading_level_report.md — Flesch–Kincaid scores for every key in the
orchestration script (doc 40 §A6).

    cd runtime && uv run python scripts/reading_level_report.py

The `intake.*` keys are ENFORCED in CI (tests/test_intake_reading_level.py: ≤ 5.9, and a glossed
term only beside its gloss). Every OTHER key is REPORT-ONLY: they were authored to the earlier
7th-grade floor, and whether they are rewritten is Brock's call (doc 40 open question 4). The
report carries no date on purpose — it changes only when the copy does, so a diff is a signal.
"""

from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from app.intake.reading_level import GRADE_CEILING, PROSE_MIN_WORDS, read, screen_glosses  # noqa: E402

REPO = pathlib.Path(__file__).resolve().parents[2]
OUT = REPO / "docs/build-kit/reading_level_report.md"


def build() -> str:
    import logging

    logging.disable(logging.CRITICAL)
    from app.agents.context_loader import load_orchestration_script

    script = load_orchestration_script()
    glosses = screen_glosses(script)
    intake = {k: v for k, v in script.items() if k.startswith("intake.")}
    other = {k: v for k, v in script.items() if not k.startswith("intake.")}

    def row(key: str, text: str, exempt: frozenset[str]) -> tuple[str, str, str, int]:
        r = read(text, exempt=exempt)
        score = f"{r.grade:.1f}" if r.is_prose else "label"
        verdict = "ok" if r.passes() else ("OVER" if r.is_prose else f"long word: {r.longest_word}")
        return score, verdict, key, r.words

    rows_other = [row(k, v, frozenset()) for k, v in other.items()]
    rows_intake = [row(k, v, glosses.get(k.split(".")[1], frozenset())) for k, v in intake.items()]
    over = [r for r in rows_other if r[1] != "ok"]
    prose = [r for r in rows_other if r[0] != "label"]
    grades = sorted(float(r[0]) for r in prose)
    median = grades[len(grades) // 2] if grades else 0.0

    lines = [
        "# Reading level of the copy registry — report",
        "",
        "Generated by `runtime/scripts/reading_level_report.py` from "
        "`intelligence-layer/prompts/orchestration_script.md`. Regenerate after any copy change.",
        "",
        f"**Standard (doc 40 §A6):** Flesch–Kincaid grade ≤ {GRADE_CEILING}. Strings under "
        f"{PROSE_MIN_WORDS} words are scored by a label rule instead (no word over 3 syllables) — "
        "the formula is defined on prose, and a one-word button scores as college reading.",
        "",
        "## Enforced — the `intake.*` keys",
        "",
        f"{len(rows_intake)} keys, **{sum(1 for r in rows_intake if r[1] != 'ok')} over**. CI fails "
        "on any key over the ceiling, and on any glossed term (deductible, coinsurance, EOB, "
        "out-of-pocket, SBC, MSN, itemized) used on a screen that does not carry its "
        "`gloss_<term>` key (`tests/test_intake_reading_level.py`).",
        "",
        "## Report-only — every other key",
        "",
        f"{len(rows_other)} keys authored to the earlier 7th-grade floor: **{len(over)} would fail** "
        f"the grade-5 standard ({len(rows_other) - len(over)} pass as they stand); the median "
        f"prose key reads at grade {median:.1f}. Nothing here fails CI — whether these are "
        "rewritten, or grandfathered until touched, is Brock's call (doc 40 open question 4). "
        "Scored WITHOUT gloss exemptions: these screens carry no gloss keys, so a term like "
        "\"deductible\" counts at its full four syllables.",
        "",
        "| key | words | FK grade | vs 5.9 |",
        "|---|---:|---:|---|",
    ]
    for score, verdict, key, words in sorted(rows_other, key=lambda r: (r[1] == "ok", -float(r[0]) if r[0] != "label" else 0)):
        lines.append(f"| `{key}` | {words} | {score} | {verdict} |")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    OUT.write_text(build(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}")
